import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

export function PasswordResetPage({ onPageChange }: { onPageChange: (page: string) => void }) {
  const [ready, setReady] = useState(false); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!supabase) { setError('Password reset is unavailable.'); return; } const { data: { subscription } } = supabase.auth.onAuthStateChange(event => { if (event === 'PASSWORD_RECOVERY' || event === 'SIGNED_IN') setReady(true); }); supabase.auth.getSession().then(({ data }) => setReady(Boolean(data.session))); return () => subscription.unsubscribe(); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setMessage(''); if (password.length < 8) { setError('Use at least 8 characters.'); return; } if (password !== confirmation) { setError('Passwords do not match.'); return; } const { error: updateError } = await supabase!.auth.updateUser({ password }); if (updateError) { setError('Unable to update the password. Request a new reset email and try again.'); return; } await supabase!.auth.signOut(); setMessage('Password updated. You can now sign in.'); setPassword(''); setConfirmation(''); };
  return <div className="pt-16 min-h-screen flex items-center justify-center px-4 bg-gradient-to-br from-[#FFF7C0]/30 via-white to-[#6EC4DB]/10"><div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full"><h1 className="text-3xl font-bold text-gray-900 mb-2">Set a new password</h1>{!ready && !error && <p className="text-gray-600">Open this page from the recovery email.</p>}{ready && <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">New password<input className="w-full mt-1 px-4 py-3 border rounded-lg" type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e => setPassword(e.target.value)} /></label><label className="block text-sm font-medium">Confirm password<input className="w-full mt-1 px-4 py-3 border rounded-lg" type="password" autoComplete="new-password" minLength={8} required value={confirmation} onChange={e => setConfirmation(e.target.value)} /></label><button className="w-full bg-[#66AB8C] text-white py-3 rounded-lg" type="submit">Update password</button></form>}{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}{message && <p role="status" className="mt-4 text-green-700">{message}</p>}{(message || error) && <button className="mt-4 text-[#66AB8C] underline" onClick={() => onPageChange('login')}>Back to sign in</button>}</div></div>;
}
